# Generated by Django 4.2.6 on 2023-10-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLLeMensAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='md5_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
