# Generated by Django 4.2.6 on 2023-10-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLLeMensAPI', '0002_alter_uploadedfile_md5_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=55)),
            ],
        ),
    ]
