# Generated by Django 4.2.6 on 2023-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLLeMensAPI', '0003_openaitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedFileTyps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=55)),
            ],
        ),
    ]
